cargo-features = ["strip"]

[workspace]
members = ["main", "keyboard-core"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
strip = "symbols"  # Automatically strip symbols from the binary.
lto = true
