cargo-features = ["strip"]

[workspace]
members = ["main", "usb"]

[profile.dev]
panic = "abort"
lto = true

[profile.release]
panic = "abort"
strip = "symbols"  # Automatically strip symbols from the binary.
lto = true
