[workspace]
members = ["necoboard-petit", "necoboard-petit-ec", "necoboard-v1", "rustkbd", "rustkbd-macros"]
resolver = "2"

[profile.dev]
panic = "abort"
debug = 1

[profile.release]
panic = "abort"
lto = true
debug = 1
