mod connection;
mod error;
mod message;
mod split_communicator;
mod split_key_switches;
mod split_state;
pub use connection::Connection;
pub(crate) use connection::ConnectionExt;
pub use error::Error;
pub(crate) use message::Message;
pub(crate) use split_communicator::SplitCommunicator;
pub use split_key_switches::{SplitKeySwitchIdentifier, SplitKeySwitches};
pub use split_state::SplitState;
